#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""GUI常量定义"""

# 卡片尺寸
CARD_WIDTH = 240
THUMB_WIDTH = 220
THUMB_HEIGHT = 124
THUMB_RADIUS = 8
CARD_RADIUS = 12

# 布局间距
LAYOUT_MARGIN = 20
CARD_SPACING = 16
SCROLLBAR_WIDTH = 8

# 尺寸限制
MIN_CARD_WIDTH = 200
MAX_CARD_WIDTH = 280
MAX_CARDS_PER_BATCH = 50
SCAN_BATCH_SIZE = 5

# 延迟时间（毫秒）
AUTO_SCAN_DELAY = 500
LAYOUT_UPDATE_DELAY = 50
WATCHER_DELAY = 2000
PREVIEW_DURATION = 30
PREVIEW_CLEANUP_DELAY = 10000

# 文件大小阈值（MB）
VIDEO_SIZE_THRESHOLD = 1
LARGE_FILE_THRESHOLD = 100

# 最大列数
MAX_GRID_COLUMNS = 5
DEFAULT_GRID_COLUMNS = 3

# 缩略图比例
THUMB_ASPECT_RATIO = 9 / 16

# 进度更新频率（秒）
PROGRESS_UPDATE_INTERVAL = 0.5

# 日志限制
MAX_LOG_LINES = 1000
MAX_VIDEO_TITLE_LENGTH = 50
MAX_FILENAME_LENGTH = 200

# 按钮尺寸
BUTTON_MIN_HEIGHT = 28
BUTTON_MIN_WIDTH = 80
SMALL_BUTTON_SIZE = 80